package interfaz;

import Dao.VentaDAO;
import Modelo.Reportes;
import Modelo.Venta;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arigo
 */
public class PanelReportes extends javax.swing.JPanel {
    VentaDAO VDao = new VentaDAO();
    Venta Venta= new Venta();
    DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form PanelReportes
     */
    
    public PanelReportes() {
        initComponents();
        lblVentasRealizadas.setText("0");
        lblIngresosTotales.setText("0.00");
    }

    public void actualizarContadores(double montoNuevo) {
        try {
            int ventasActuales = Integer.parseInt(lblVentasRealizadas.getText());
            lblVentasRealizadas.setText(String.valueOf(ventasActuales + 1));

            double ingresosActuales = Double.parseDouble(lblIngresosTotales.getText());
            double nuevoTotal = ingresosActuales + montoNuevo;
            lblIngresosTotales.setText(String.format("%.2f", nuevoTotal));
        } catch (NumberFormatException e) {
            System.out.println("Error al actualizar: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStockBajo = new javax.swing.JTable();
        btnReporteCompleto = new javax.swing.JButton();
        btnCerrarTurno = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblVentasRealizadas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblIngresosTotales = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        BTNuevoTurno = new javax.swing.JButton();
        btnExportarStockBajo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVentas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnBuscarReporte = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel34.setBackground(new java.awt.Color(255, 161, 189));

        jPanel3.setBackground(new java.awt.Color(255, 255, 231));
        jPanel3.setPreferredSize(new java.awt.Dimension(467, 324));

        jPanel2.setBackground(new java.awt.Color(255, 161, 189));

        jLabel13.setBackground(new java.awt.Color(255, 161, 189));
        jLabel13.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel13.setText("REPORTES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableStockBajo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IDProducto", "Producto", "Stock"
            }
        ));
        jScrollPane1.setViewportView(jTableStockBajo);

        btnReporteCompleto.setBackground(new java.awt.Color(255, 161, 189));
        btnReporteCompleto.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnReporteCompleto.setText("Exportar reporte completo");
        btnReporteCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteCompletoActionPerformed(evt);
            }
        });

        btnCerrarTurno.setBackground(new java.awt.Color(255, 102, 102));
        btnCerrarTurno.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnCerrarTurno.setText("Cerrar turno");
        btnCerrarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarTurnoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setText("Fecha inicio:");

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setText("Fecha fin:");

        jPanel35.setBackground(new java.awt.Color(197, 255, 135));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel15.setText("Ventas totales:");

        jLabel2.setText("Ventas Realizadas:");

        lblVentasRealizadas.setText("jLabel3");

        jLabel5.setText("Ingresos Totales:");

        lblIngresosTotales.setText("jLabel3");

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIngresosTotales))
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVentasRealizadas)))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel35Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(60, 60, 60))
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblVentasRealizadas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIngresosTotales)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDateChooser1.setBackground(new java.awt.Color(255, 204, 255));

        jDateChooser2.setBackground(new java.awt.Color(255, 204, 255));

        BTNuevoTurno.setBackground(new java.awt.Color(255, 161, 189));
        BTNuevoTurno.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        BTNuevoTurno.setText("Nuevo Turno");
        BTNuevoTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNuevoTurnoActionPerformed(evt);
            }
        });

        btnExportarStockBajo.setBackground(new java.awt.Color(105, 229, 255));
        btnExportarStockBajo.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnExportarStockBajo.setText("Exportar");
        btnExportarStockBajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarStockBajoActionPerformed(evt);
            }
        });

        jTableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IDVenta", "ID Producto", "Cantidad", "Total"
            }
        ));
        jScrollPane2.setViewportView(jTableVentas);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Productos con stock bajo:");

        btnBuscarReporte.setBackground(new java.awt.Color(105, 229, 255));
        btnBuscarReporte.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnBuscarReporte.setText("Buscar");
        btnBuscarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(78, 78, 78)
                                    .addComponent(jLabel4)
                                    .addGap(15, 15, 15))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                    .addComponent(btnBuscarReporte))))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnExportarStockBajo)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(btnReporteCompleto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCerrarTurno))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BTNuevoTurno)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BTNuevoTurno)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarReporte))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExportarStockBajo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrarTurno))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReporteCompleto)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteCompletoActionPerformed
    Reportes rep = new Reportes();
    rep.exportarReporteCompleto(jTableStockBajo, jTableVentas); 
    }//GEN-LAST:event_btnReporteCompletoActionPerformed

    private void btnCerrarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarTurnoActionPerformed
    String totalVentas = lblVentasRealizadas.getText();
    String totalDinero = lblIngresosTotales.getText();
    
    int respuesta = JOptionPane.showConfirmDialog(null, 
        "RESUMEN DE CIERRE:\n" +
        "Ventas: " + totalVentas + "\n" +
        "Total Caja: $" + totalDinero + "\n\n" +
        "¿Deseas exportar el reporte completo antes de cerrar?", 
        "Confirmar Cierre de Turno", JOptionPane.YES_NO_CANCEL_OPTION);
        
    if (respuesta == JOptionPane.YES_OPTION) {
        Reportes r = new Reportes();
        r.exportarReporteCompleto(jTableStockBajo, jTableVentas);
        limpiarPantallaCierre(); 
    } else if (respuesta == JOptionPane.NO_OPTION) {
        limpiarPantallaCierre();
    }
}

private void limpiarPantallaCierre() {
    lblVentasRealizadas.setText("0");
    lblIngresosTotales.setText("0.00");
    ((DefaultTableModel)jTableVentas.getModel()).setRowCount(0);
    JOptionPane.showMessageDialog(null, "Turno cerrado y caja reiniciada.");
    }//GEN-LAST:event_btnCerrarTurnoActionPerformed

    private void btnBuscarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarReporteActionPerformed
    if (jDateChooser1.getDate() != null && jDateChooser2.getDate() != null) {
        
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String fechaI = sdf.format(jDateChooser1.getDate());
        String fechaF = sdf.format(jDateChooser2.getDate());

        double[] datos = VDao.obtenerResumenVentas(fechaI, fechaF);
        
        lblVentasRealizadas.setText(String.valueOf((int)datos[0])); 
        lblIngresosTotales.setText("$ " + String.valueOf(datos[1]));

        List<Venta> lista = VDao.filtrarVentasPorFecha(fechaI, fechaF);
        
    } else {
        JOptionPane.showMessageDialog(null, "Por favor, selecciona un rango de fechas.");
    }
    }//GEN-LAST:event_btnBuscarReporteActionPerformed

    private void btnExportarStockBajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarStockBajoActionPerformed
    Reportes reportes = new Reportes();
    
    if (jTableStockBajo.getRowCount() > 0) {
        reportes.exportarStockBajo(jTableStockBajo);
    } else {
        JOptionPane.showMessageDialog(null, "No hay productos con stock bajo para exportar.");
    }
    }//GEN-LAST:event_btnExportarStockBajoActionPerformed

    private void BTNuevoTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNuevoTurnoActionPerformed
    int confirmar = JOptionPane.showConfirmDialog(null, "¿Deseas abrir un nuevo turno?"
            + " Se limpiarán los datos actuales.");
    
    if (confirmar == JOptionPane.YES_OPTION) {
        lblVentasRealizadas.setText("0");
        lblIngresosTotales.setText("0.00");

        DefaultTableModel modelo = (DefaultTableModel) jTableVentas.getModel();
        modelo.setRowCount(0);
        
        JOptionPane.showMessageDialog(null, "Turno abierto. Los contadores están en cero.");
    }
    }//GEN-LAST:event_BTNuevoTurnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNuevoTurno;
    private javax.swing.JButton btnBuscarReporte;
    private javax.swing.JButton btnCerrarTurno;
    private javax.swing.JButton btnExportarStockBajo;
    private javax.swing.JButton btnReporteCompleto;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableStockBajo;
    private javax.swing.JTable jTableVentas;
    private javax.swing.JLabel lblIngresosTotales;
    private javax.swing.JLabel lblVentasRealizadas;
    // End of variables declaration//GEN-END:variables
}
