package Interfaz;

import Dao.ProductoDAO;
import Modelo.Producto;
import Dao.CategoriaDAO;
import Modelo.Categoria;
import Modelo.Proveedor;
import Dao.ProveedorDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arigo
 */
public class PanelInventario extends javax.swing.JPanel {
ProductoDAO pDao = new ProductoDAO();
DefaultTableModel modeloInventario = new DefaultTableModel();

public PanelInventario() {
    initComponents();
    llenarCombos();

    DefaultTableModel modelo = (DefaultTableModel) jTableInv.getModel();
    modelo.setRowCount(0); 
}

public void listarProductosInventario() {
    List<Producto> lista = pDao.listar();
    modeloInventario = (DefaultTableModel) jTableInv.getModel();
    modeloInventario.setRowCount(0);
    Object[] ob = new Object[8];
    for (int i = 0; i < lista.size(); i++) {
        ob[0] = lista.get(i).getIdProducto();
        ob[1] = lista.get(i).getNomProd();
        ob[2] = lista.get(i).getIdCategoria(); 
        ob[3] = lista.get(i).getPrecio();
        ob[4] = lista.get(i).getIdProveedor();
        ob[5] = lista.get(i).getStock();
        ob[6] = lista.get(i).getStockMin();
        ob[7] = lista.get(i).getCodigoBarras();
        modeloInventario.addRow(ob);
    }
}
private void llenarCombos() {
    CategoriaDAO catDao = new CategoriaDAO();
    ProveedorDAO provDao = new ProveedorDAO();

    try {
        List<Categoria> listaCat = catDao.listar();
        InventarioCBCat.removeAllItems();
        InventarioCBCat.addItem("Seleccionar Categoría");
        for (Categoria cat : listaCat) {
            InventarioCBCat.addItem(cat.getNombreCat());
        }
    } catch (Exception e) {
        System.out.println("Error al cargar combos de categorías: " + e.getMessage());
    }

    try {
        List<Proveedor> listaProv = provDao.listar();
        InventarioCBProv.removeAllItems();
        InventarioCBProv.addItem("Seleccionar Proveedor");
        for (Proveedor prov : listaProv) {
            InventarioCBProv.addItem(prov.getNomProv());
        }
    } catch (Exception e) {
        System.out.println("Error al cargar combos de proveedores: " + e.getMessage());
    }

    InventarioCBEstado.removeAllItems();
    InventarioCBEstado.addItem("Seleccionar Estado");
    InventarioCBEstado.addItem("Activo");
    InventarioCBEstado.addItem("Inactivo");
    InventarioCBEstado.addItem("Agotado");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        InventarioCBEstado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        InventarioBTBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInv = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        InventarioBTStock = new javax.swing.JButton();
        InventarioCBProv = new javax.swing.JComboBox<>();
        InventarioCBCat = new javax.swing.JComboBox<>();
        InventarioBTPrecio = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        InventarioStock = new javax.swing.JTextField();
        InventarioPU = new javax.swing.JTextField();
        InventarioPM = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(243, 175, 250));

        jPanel3.setBackground(new java.awt.Color(255, 255, 231));
        jPanel3.setPreferredSize(new java.awt.Dimension(467, 324));

        jPanel2.setBackground(new java.awt.Color(243, 175, 250));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("INVENTARIO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Proveedor:");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Estado:");

        InventarioCBEstado.setBackground(new java.awt.Color(255, 238, 111));
        InventarioCBEstado.setEditable(true);
        InventarioCBEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Categoría:");

        InventarioBTBuscar.setBackground(new java.awt.Color(197, 255, 135));
        InventarioBTBuscar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        InventarioBTBuscar.setText("Buscar");
        InventarioBTBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioBTBuscarActionPerformed(evt);
            }
        });

        jTableInv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Producto", "Categoría", "Precio", "Proveedor", "Stock", "Stock min", "Codigo", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTableInv);

        jPanel7.setBackground(new java.awt.Color(255, 255, 231));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        InventarioBTStock.setBackground(new java.awt.Color(197, 255, 135));
        InventarioBTStock.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        InventarioBTStock.setText("Modificar Stock");
        InventarioBTStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioBTStockActionPerformed(evt);
            }
        });

        InventarioCBProv.setBackground(new java.awt.Color(255, 238, 111));
        InventarioCBProv.setEditable(true);
        InventarioCBProv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        InventarioCBCat.setBackground(new java.awt.Color(255, 238, 111));
        InventarioCBCat.setEditable(true);
        InventarioCBCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        InventarioBTPrecio.setBackground(new java.awt.Color(197, 255, 135));
        InventarioBTPrecio.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        InventarioBTPrecio.setText("Modificar Precio");
        InventarioBTPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioBTPrecioActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Stock: ");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("Precio Unitario:");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("Precio Mayoreo:");

        InventarioStock.setBackground(new java.awt.Color(255, 238, 111));

        InventarioPU.setBackground(new java.awt.Color(255, 238, 111));

        InventarioPM.setBackground(new java.awt.Color(255, 238, 111));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InventarioBTStock)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InventarioStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InventarioPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(InventarioBTPrecio)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InventarioPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(InventarioCBEstado, 0, 185, Short.MAX_VALUE)
                                .addComponent(InventarioCBProv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(InventarioCBCat, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(InventarioBTBuscar)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(17, 17, 17))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InventarioCBProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(InventarioCBCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(InventarioCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InventarioBTBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(InventarioPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(InventarioStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(InventarioPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(InventarioBTStock))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InventarioBTPrecio)))))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InventarioBTBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioBTBuscarActionPerformed
   Object itemProv = InventarioCBProv.getSelectedItem();
String proveedor = (itemProv != null) ? itemProv.toString() : "Seleccionar Proveedor";

Object itemCat = InventarioCBCat.getSelectedItem();
String categoria = (itemCat != null) ? itemCat.toString() : "Seleccionar Categoría";

Object itemEstado = InventarioCBEstado.getSelectedItem();
String estado = (itemEstado != null) ? itemEstado.toString() : "Seleccionar Estado";

List<Producto> lista = pDao.buscarPorFiltros(proveedor, categoria, estado);

    modeloInventario = (DefaultTableModel) jTableInv.getModel();
    modeloInventario.setRowCount(0);

    Object[] ob = new Object[9];

    for (Producto p : lista) {
        ob[0] = p.getIdProducto();
        ob[1] = p.getNomProd();
        ob[2] = p.getCategoria();
        ob[3] = p.getPrecio();
        ob[4] = p.getProveedor();
        ob[5] = p.getStock();
        ob[6] = p.getStockMin();
        ob[7] = p.getCodigoBarras();
        ob[8] = p.getEstado();// o lo que tengas

        modeloInventario.addRow(ob);
    }
    }//GEN-LAST:event_InventarioBTBuscarActionPerformed

    private void InventarioBTPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioBTPrecioActionPerformed
    int fila = jTableInv.getSelectedRow();
    
    if (fila != -1) {
        if (!InventarioPU.getText().isEmpty()) {
            try {
                int id = Integer.parseInt(jTableInv.getValueAt(fila, 0).toString());
                double nuevoPrecio = Double.parseDouble(InventarioPU.getText());

                if (pDao.editarCampos("Precio", nuevoPrecio, id)) {
                    JOptionPane.showMessageDialog(null, "Precio actualizado correctamente");
                    
                    InventarioPU.setText("");
                    listarProductosInventario(); 
                } else {
                    JOptionPane.showMessageDialog(null, "Error al actualizar en la base de datos");
                }
                
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Por favor, ingrese un precio válido (ej: 10.50)");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese el nuevo precio en el cuadro de texto");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Seleccione un producto de la tabla para modificar su precio");

}
    }//GEN-LAST:event_InventarioBTPrecioActionPerformed

    private void InventarioBTStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioBTStockActionPerformed
    int fila = jTableInv.getSelectedRow();
    if (fila != -1) {
        int id = Integer.parseInt(jTableInv.getValueAt(fila, 0).toString());
       String texto = InventarioStock.getText().trim();

if (texto.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Ingresa un valor en Stock");
    return;
}

int stock = Integer.parseInt(texto);

if (pDao.actualizarStockYEstado(stock, id)) {
    JOptionPane.showMessageDialog(null, "Stock actualizado");
    listarProductosInventario();
}
      
    } else {
        JOptionPane.showMessageDialog(null, "Seleccione un producto de la tabla");
    }
    }//GEN-LAST:event_InventarioBTStockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InventarioBTBuscar;
    private javax.swing.JButton InventarioBTPrecio;
    private javax.swing.JButton InventarioBTStock;
    private javax.swing.JComboBox<String> InventarioCBCat;
    private javax.swing.JComboBox<String> InventarioCBEstado;
    private javax.swing.JComboBox<String> InventarioCBProv;
    private javax.swing.JTextField InventarioPM;
    private javax.swing.JTextField InventarioPU;
    private javax.swing.JTextField InventarioStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableInv;
    // End of variables declaration//GEN-END:variables
}
